### ISSUE TITLE
Meaningful messages

### ISSUE THREAD

**Issue by animeshsingh** [IBM/Java-MicroProfile-Microservices-on-Istio#3]
@Tomcli rather than returning error messages for circuit breakers and fault tolerance, does istio allow you return a more meaningful message?

**Comment by Tomcli** [comment]
For circuit breakers and fault tolerance, istio will only return the HTTP 5xx server error code. So from the client side it is hard to tell whether the error is from the Cloudant server or circuit breaker/fault tolerance. 

For now, we can check the logs from Cloudant's envoy to determine whether the requests is rejected from circuit breaker or Cloudant.

**Comment by animeshsingh** [comment]
Ok - we should show those stats. Also timeouts and retries are part of fault tolerance aspects. Please make those sections a bit more clear and dive a bit deeper - something like what`s done in the blogs here....

https://blog.openshift.com/microservices-patterns-envoy-part-i/
https://blog.openshift.com/microservices-patterns-envoy-proxy-part-ii-timeouts-retries/

**Comment by animeshsingh** [comment]
Also look at what type of circuit breaking we are showing https://lyft.github.io/envoy/docs/intro/arch_overview/circuit_breaking.html#arch-overview-circuit-break

**Comment by animeshsingh** [comment]
@Tomcli So I added this blurb at top: 

Resiliency and fault tolerance: Istio adds fault tolerance to your application without any changes to code. Some of resiliency features it supports are:

Retries/Timeouts
Circuit breakers
Health checks
Control connection pool size and request load
Systematic fault injection

In this code we will show how to configure and use Circuit Breakers, Fault Injection and Retries/Timeouts resiliency features for your Java Microservices application.

Lets see if we can show the three individually?

**Comment by Tomcli** [comment]
For the type of circuit breaking, you can customize it to do maximum connections, maximum pending requests, and maximum requests.

**Comment by Tomcli** [comment]
In terms of showing it, right now i'm searching where do they show all the upstream logs to and use those logs to show some meaningful stats.

**Comment by animeshsingh** [comment]
Yeah you don't need to show all Circuit breakers types - pick a couple and dive a bit deeper

Think for each of these sections - circuit breaker, fault injection, retries/timeouts your section is a little blog for each explaining what they are, how to use it and finally how to show they were actually triggered
