### ISSUE TITLE
Anyuid problem on istio-proxy

### ISSUE THREAD

**Issue by gbaufake** [IBM/Java-MicroProfile-Microservices-on-Istio#35]
Hello, I was trying to follow this tutorial on openshift and I got this message

> Error creating: pods "microservice-schedule-sample-2508702501-" is forbidden: unable to validate against any security context constraint: [provider anyuid: .spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "NET_ADMIN": capability may not be added provider anyuid: .spec.initContainers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed securityContext.runAsUser: Invalid value: 1001: UID on container istio-init does not match required range. Found 1001, required min: 1000320000 max: 1000329999

**Comment by kuramal** [comment]
did you resolved the problem? I got the same

**Comment by kuramal** [comment]
I resolved the problem with add the dafault sa to scc: 
oc adm policy add-scc-to-user privileged -z default -n you_app_namespace

**Comment by gbaufake** [comment]
thanks @kuramal

**Comment by 0xj4f** [comment]
> I resolved the problem with add the dafault sa to scc:
> oc adm policy add-scc-to-user privileged -z default -n you_app_namespace

@kuramal 
Solved my problem too, Thank you!

**Comment by its-saurabhjain** [comment]
i am getting the same issue but setting the above did not resolved my issue...

**Comment by jetendralaha** [comment]
> I resolved the problem with add the dafault sa to scc:
> oc adm policy add-scc-to-user privileged -z default -n you_app_namespace

thanks !!!!!
